Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	run_dnabc
	1

rule run_dnabc:
    input: /mnt/isilon/microbiome/raw_data/190520_M03543_0158_000000000-CGCHB_L001/Undetermined_S0_L001_R1_001.fastq.gz, /mnt/isilon/microbiome/raw_data/190520_M03543_0158_000000000-CGCHB_L001/Undetermined_S0_L001_R2_001.fastq.gz, /scr1/users/leej39/Mehrara/Mehrara_Run_1_mapping_file.tsv
    output: /scr1/users/leej39/Mehrara/demultiplexed_fastq/Human.lymph.arm.skinswab.4_R1.fastq
    jobid: 0
    wildcards: sample=Human.lymph.arm.skinswab.4, direction=R1


        dnabc.py         --output-dir /scr1/users/leej39/Mehrara/demultiplexed_fastq         --mismatches 0         --manifest-file /scr1/users/leej39/Mehrara/manifest.csv         --total-reads-file /scr1/users/leej39/Mehrara/total_read_counts.tsv         /scr1/users/leej39/Mehrara/Mehrara_Run_1_mapping_file.tsv /mnt/isilon/microbiome/raw_data/190520_M03543_0158_000000000-CGCHB_L001/Undetermined_S0_L001_R1_001.fastq.gz /mnt/isilon/microbiome/raw_data/190520_M03543_0158_000000000-CGCHB_L001/Undetermined_S0_L001_R2_001.fastq.gz
        
Error in rule run_dnabc:
    jobid: 0
    output: /scr1/users/leej39/Mehrara/demultiplexed_fastq/Human.lymph.arm.skinswab.4_R1.fastq

RuleException:
CalledProcessError in line 18 of /scr1/users/leej39/16S_QIIME2/rules/demux/dnabc.rules:
Command ' set -euo pipefail;  
        dnabc.py         --output-dir /scr1/users/leej39/Mehrara/demultiplexed_fastq         --mismatches 0         --manifest-file /scr1/users/leej39/Mehrara/manifest.csv         --total-reads-file /scr1/users/leej39/Mehrara/total_read_counts.tsv         /scr1/users/leej39/Mehrara/Mehrara_Run_1_mapping_file.tsv /mnt/isilon/microbiome/raw_data/190520_M03543_0158_000000000-CGCHB_L001/Undetermined_S0_L001_R1_001.fastq.gz /mnt/isilon/microbiome/raw_data/190520_M03543_0158_000000000-CGCHB_L001/Undetermined_S0_L001_R2_001.fastq.gz ' returned non-zero exit status 1.
  File "/scr1/users/leej39/16S_QIIME2/rules/demux/dnabc.rules", line 18, in __rule_run_dnabc
  File "/home/leej39/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job run_dnabc since they might be corrupted:
/scr1/users/leej39/Mehrara/demultiplexed_fastq/Human.lymph.arm.skinswab.4_R1.fastq
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /scr1/users/leej39/16S_QIIME2/.snakemake/log/2019-07-22T145436.364649.snakemake.log
